### ISSUE TITLE
Error while running make file

### ISSUE THREAD

**Issue by ghost** [definepi314/crazyflie-matlab-client#1]
I am having this error while running make file.. 

Error using mex
/tmp/mex_20430030877419_3861/sfun_cflie_simple.o: In function mdlStart(SimStruct_tag*)': sfun_cflie_simple.cpp:(.text+0x559): undefined reference toCCrazyRadio::CCrazyRadio(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2: error: ld returned 1 exit status

Kindly advice.
Thank you.

**Comment by definepi314** [comment]
Hi,

Steps to install/run Crazyflie simulink block

   1. Download Crazyflie simulink library (CF_lib) attached
   2. Open Matlab and change workspace to the folder containing the CF_lib
   3. Setup C++ compiler by typing the command  mex -setup C++
   4. In the make.m file edit the pathToLibCFLIE to the actual path where
   you stored the libclfie.so.  mex -v CFLAGS='$CFLAGS -fPIC'
   -LpathToLIBCFLIE -lcflie -lusb-1.0 sfun_cflie_simple.cp
   5. Once compiled successfully you should be able to run the simulink
   test_simple.slx

If you still getting error, try using the attached cpp file instead
instead of the zipped one.

**Comment by ghost** [comment]
Hi..

 Thanks MEX was successful but while running Simulnk test simple.slx file I got the error-

Error while obtaining sizes from MEX S-function 'sfun_cflie_simple' in 'test_simple/S-Function1'.
Caused by:
Invalid MEX-file '/home/gavtech/Documents/crazyflie-client-matlab/CrazyFlie_lib/sfun_cflie_simple.mexa64': libcflie.so: cannot open shared object file: No such file or directory.

**Comment by definepi314** [comment]
Hey,

That error is because the libcflie.so is not in the permanent path general
path of Matlab. This means that no matter what you have the current
workspace is, Matlab has access to those folders/files. You need to add it
to the path. You can do two things

1. Add the folder containing the libcflie.so to the list of Matlab paths.
Do this by clicking on "Set Path" in the toolbar and selecting "add folder"

2. Copy the libcflie.so to a folder that is already on the path i.e.
default Matlab folder, or linux usr/lib folder

Best,
Ishan.

**Comment by ghost** [comment]
Hello,

  Thank you that error was resolved. I now have the simulation running but I cannot see any other activity. The quadcopter does not respond to it. I have added a picture for my simulation.. 
![Simulink pic](https://user-images.githubusercontent.com/28192394/85769116-fde61080-b719-11ea-9d76-0abe23ffcb74.jpeg)

Kindly advice.
Thank you.

**Comment by definepi314** [comment]
Hi,

This was implemented some time back so I don't exactly remember all the nitty gritty details. There seems to be some connectivity issues between crazyflie and bluetooth. You can see this link for reference. It is a video I recorded of its working. You can see the changing values on Display which crazyflie sends of its orientation which seems to be missing in your pic.
https://drive.google.com/file/d/0ByP1gZmXf9lkc3loUE5DaGRXMTA/view?usp=sharing

Best,
Ishan.

**Comment by ghost** [comment]
Dear ISHAN,
    
     Thank you for your valuable advice and time. I really appreciate your effort. Yes, its working now. The problem was with the radio address. Silly mistake though. I also wish you good luck.

Best regards
Gaurav

**Comment by definepi314** [comment]
Thanks and all the best!
